"""
Run 5 baselines on 5 curriculum levels (generated by world_gen).

Setup:
  5 curriculum levels (0.0, 0.25, 0.50, 0.75, 1.0)
  5 baselines (Random, NaivePattern, CausalLearner, CausalReasoner, Oracle)
  3 seeds per level per baseline = 75 episodes total

Output: Reward vs difficulty, shows how each baseline scales with curriculum.
"""

import numpy as np
from concurrent.futures import ProcessPoolExecutor, as_completed
import sys

from world_gen import curriculum_knobs, describe_difficulty, generate_config, validate_config

from fishing_game.simulator import FishingGameEnv
from fishing_game.evaluator import Evaluator
from fishing_game.baselines import (
    RandomAgent, NaivePatternMatcher, CausalLearner,
    CausalReasoner, OracleAgent,
)

BASELINES = [
    ("Random", RandomAgent),
    ("NaivePattern", NaivePatternMatcher),
    ("CausalLearner", CausalLearner),
    ("CausalReasoner", CausalReasoner),
    ("Oracle", OracleAgent),
]

CURRICULUM_LEVELS = [0.0, 0.25, 0.5, 0.75, 1.0]
SEEDS_PER_LEVEL = [42, 123, 456]  # 3 seeds per level


def run_episode(agent_name, agent_cls, level, seed, cfg):
    """Run single episode on a specific curriculum level."""
    env = FishingGameEnv(config=cfg)
    obs = env.reset(seed=seed)
    agent = agent_cls(config=cfg)
    if hasattr(agent, "reset"):
        agent.reset()

    total_reward = 0.0
    for _ in range(cfg["episode_length"]):
        result = agent.act(env, obs)
        total_reward += result["reward"]
        if result["done"]:
            break
        obs = result["observation"]

    trace = env.get_trace()
    evaluator = Evaluator(config=cfg)
    eval_result = evaluator.evaluate_episode(trace)

    return {
        "agent": agent_name,
        "level": level,
        "seed": seed,
        "total_reward": eval_result.get("total_reward", total_reward),
        "mean_brier_storm": eval_result.get("mean_brier_storm", 0),
        "mean_brier_equip": eval_result.get("mean_brier_equip", 0),
        "total_inference_gap": eval_result.get("total_inference_gap", 0),
    }


def main():
    print("=" * 100)
    print("CURRICULUM BASELINE SWEEP: 5 levels × 5 baselines × 3 seeds")
    print("=" * 100)

    # Generate configs for all 5 curriculum levels
    print("\n[Generating curriculum configs...]")
    configs = {}
    for level in CURRICULUM_LEVELS:
        knobs = curriculum_knobs(level)
        cfg = generate_config(knobs, seed=42)
        validate_config(cfg, strict=False)
        configs[level] = cfg
        print(f"  Level {level:.2f}: d_prime={knobs.d_prime:.2f}, "
              f"alpha={knobs.transition_alpha:.2f}, "
              f"zones={knobs.sensor_zones}/4, "
              f"asymmetry={knobs.reward_asymmetry:.1f}x")

    print(f"\n[Running {len(CURRICULUM_LEVELS) * len(BASELINES) * len(SEEDS_PER_LEVEL)} episodes...]")

    results_by_agent_level = {}
    for agent_name, _ in BASELINES:
        results_by_agent_level[agent_name] = {level: [] for level in CURRICULUM_LEVELS}

    # Run all episodes in parallel
    tasks = []
    with ProcessPoolExecutor(max_workers=6) as executor:
        for level in CURRICULUM_LEVELS:
            cfg = configs[level]
            for agent_name, agent_cls in BASELINES:
                for seed in SEEDS_PER_LEVEL:
                    future = executor.submit(
                        run_episode, agent_name, agent_cls, level, seed, cfg
                    )
                    tasks.append(future)

        completed = 0
        for future in as_completed(tasks):
            result = future.result()
            results_by_agent_level[result["agent"]][result["level"]].append(result)
            completed += 1
            print(f"[{completed:>2}/{len(tasks)}] Level {result['level']:.2f} "
                  f"{result['agent']:<16} seed={result['seed']:<4} reward={result['total_reward']:>7.1f}")

    # === RESULTS TABLE ===
    print("\n" + "=" * 100)
    print("RESULTS BY CURRICULUM LEVEL")
    print("=" * 100)

    for level in CURRICULUM_LEVELS:
        print(f"\n--- LEVEL {level:.2f} ---")
        print(f"{'Agent':<16} {'Mean':>8} {'Std':>7}  Per-seed")
        print("-" * 70)

        for agent_name, _ in BASELINES:
            evals = results_by_agent_level[agent_name][level]
            rewards = [e["total_reward"] for e in evals]
            mean_reward = np.mean(rewards)
            std_reward = np.std(rewards)
            per_seed = "  ".join(f"s{e['seed']}={e['total_reward']:.0f}" for e in evals)
            print(f"{agent_name:<16} {mean_reward:>8.1f} {std_reward:>6.1f}  {per_seed}")

    # === SUMMARY TABLE: Mean reward per agent across all levels ===
    print("\n" + "=" * 100)
    print("SUMMARY: Mean Reward by Agent (averaged across seeds)")
    print("=" * 100)
    print(f"\n{'Agent':<16}", end="")
    for level in CURRICULUM_LEVELS:
        print(f" Level{level:>4.2f}", end="")
    print()
    print("-" * 70)

    for agent_name, _ in BASELINES:
        print(f"{agent_name:<16}", end="")
        for level in CURRICULUM_LEVELS:
            evals = results_by_agent_level[agent_name][level]
            rewards = [e["total_reward"] for e in evals]
            mean_reward = np.mean(rewards)
            print(f" {mean_reward:>7.1f}", end="")
        print()

    # === DIFFICULTY SCALING ANALYSIS ===
    print("\n" + "=" * 100)
    print("DIFFICULTY SCALING: How each agent's reward changes with curriculum level")
    print("=" * 100)

    for agent_name, _ in BASELINES:
        rewards_per_level = []
        for level in CURRICULUM_LEVELS:
            evals = results_by_agent_level[agent_name][level]
            rewards = [e["total_reward"] for e in evals]
            mean_reward = np.mean(rewards)
            rewards_per_level.append(mean_reward)

        # Compute difficulty scaling
        delta_easy_hard = rewards_per_level[0] - rewards_per_level[-1]  # Level 0.0 - 1.0
        sensitivity = delta_easy_hard / 1.0  # Change per unit difficulty

        print(f"\n{agent_name}:")
        print(f"  Easy (L0.0): {rewards_per_level[0]:>7.1f}")
        print(f"  Hard (L1.0): {rewards_per_level[-1]:>7.1f}")
        print(f"  Gap:         {delta_easy_hard:>7.1f} points")
        print(f"  Sensitivity: {sensitivity:>7.1f} points/difficulty unit")

    # === INFERENCE GAP ANALYSIS ===
    print("\n" + "=" * 100)
    print("INFERENCE GAP BY LEVEL (How partial observability hurts)")
    print("=" * 100)

    for level in CURRICULUM_LEVELS:
        print(f"\nLevel {level:.2f}:")
        print(f"{'Agent':<16} {'Avg InfGap':>12}")
        print("-" * 35)

        for agent_name, _ in BASELINES:
            evals = results_by_agent_level[agent_name][level]
            inf_gaps = [e["total_inference_gap"] for e in evals]
            mean_inf_gap = np.mean(inf_gaps)
            print(f"{agent_name:<16} {mean_inf_gap:>12.1f}")


if __name__ == "__main__":
    main()
